@startuml

Actor User
participant Merchant
participant Vipps_frontend
participant Vipps

Merchant -> Vipps : Define Webhook and Redirect urls

note right
This is done using the portal, any value sent in the session
request will override the default choices
end note

User -> Merchant : Start shopping session, proceed to Checkout
Merchant -> Vipps : Start checkout session

note right 
If desired the Webhook/Redirect URLs can be defined here
taking precedence over any standard configuration
values  
end note

Vipps --> Merchant : Return Checkout session id
activate Vipps_frontend
Merchant ->o Vipps_frontend: Insert checkout session id

activate Merchant
Merchant -> Vipps : Poll on OrderID given in session setup
Vipps_frontend -> User : Display session
User -> Vipps_frontend : Complete session
Vipps_frontend -> Vipps : Process payment
Vipps --> Vipps_frontend : Payment result

group if applicable for the flow
Vipps_frontend ->o Merchant : Redirect to merchant defined URL
end
deactivate Vipps_frontend

Merchant -> Vipps: receive polling result on orderID
deactivate Merchant

Vipps --> Merchant : Session result

note right
This should be considered best practice, as a polling
based approach gives a backup solution to any fault scenario
end note

Vipps -> Merchant : Send Checkout Result to Webhook URL

note left
A standard Checkout result will 
include Transaction status,
Customer information and Shipping details
and will give the same info as the poll
on the session ID
end note

deactivate Vipps_frontend


@enduml